runtime: python311

env_variables:
  GROQ_API_KEY: "your_groq_api_key_here"
  LLM_MODEL: "llama3-70b-8192"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  RAG_RETRIEVAL_COUNT: "3"
  DEFAULT_TEMPERATURE: "0.7"
  MIN_SIMILARITY_THRESHOLD: "0.3"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4

entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true 